### ISSUE TITLE
Does not build on gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

### ISSUE THREAD

**Issue by kostinalexey** [01org/mkl-dnn#146]
### Description
Error message
src/cpu/jit_avx512_common_conv_kernel.cpp:2666:42: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
     auto emit_fma_block = [&](int kh_step) {
                                          ^

### Environment
MKL lib is from l_mkl_2018.0.128

See compiler version in the tile

### Steps to reproduce
1. clone
2. mkdir build
3. cd build
4. cmake "source_dir"
5. make -j 20

### Expected behavior
compile OK

**Comment by kostinalexey** [comment]
`
[  1%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_conv_kernel.cpp.o
cd _hidden_/mkl-dnn/build/src && /usr/bin/c++   -DMKLDNN_DLL -DMKLDNN_DLL_EXPORTS -DUSE_CBLAS -DUSE_MKL -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -Dmkldnn_EXPORTS -I/opt/intel/mkl/include -I_hidden_/mkl-dnn/include -I_hidden_/mkl-dnn/src -I_hidden_/mkl-dnn/src/common -I_hidden_/mkl-dnn/src/cpu/xbyak  -std=c++11 -fvisibility-inlines-hidden  -Wall -Werror -Wno-unknown-pragmas -fvisibility=internal -fopenmp -fPIC -Wformat -Wformat-security -fstack-protector-strong -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -fPIC   -std=gnu++11 -o CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_conv_kernel.cpp.o -c _hidden_/mkl-dnn/src/cpu/jit_avx512_common_conv_kernel.cpp
_hidden_/mkl-dnn/src/cpu/jit_avx512_common_conv_kernel.cpp: In lambda function:
_hidden_/mkl-dnn/src/cpu/jit_avx512_common_conv_kernel.cpp:2666:42: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
     auto emit_fma_block = [&](int kh_step) {
                                          ^
cc1plus: all warnings being treated as errors
`

**Comment by emfomenk** [comment]
Seems like a bug in gcc 5.4.0.
Potential fix is [here](https://gist.github.com/emfomenk/d0ac0cccef7df32ac81d539e1874c45c).
